### ISSUE TITLE
Top 10 topics in SE

### ISSUE THREAD

**Issue by bigfatnoob** [ai-se/citemap#1]
Topic 0: applications web application user approach systems framework based
Topic 1: model language design specification specifications formal models verification
Topic 2: software developers information tools development data source project
Topic 3: software based results quality metrics paper approach techniques
Topic 4: bug bugs time performance reports defects developers software
Topic 5: program analysis programs dynamic static paper technique execution
Topic 6: software engineering development research process project systems quality
Topic 7: test testing cases tests coverage generation based technique
Topic 8: code source software changes approach paper change systems
Topic 9: software model systems architecture approach component paper design

**Comment by bigfatnoob** [comment]
### Topics(x axis) vs Likelihood(y axis).

![picture1](https://cloud.githubusercontent.com/assets/5582924/15588562/8c99e370-235c-11e6-95cb-968b98edcd27.png)


## 90 topics is optimal

**Comment by bigfatnoob** [comment]
'1','ICSE',NULL,'117'
'2','ICSM',NULL,'53'
'3','WCRE',NULL,'43'
'4','CSMR',NULL,'40'
'5','MSR',NULL,'32'
'6','GPCE',NULL,'37'
'7','FASE',NULL,'42'
'8','ICPC',NULL,'43'
'9','FSE',NULL,'59'
'10','SCAM',NULL,'15'
'11','ASE',NULL,'55'

**Comment by amritbhanu** [comment]
Stability Scores reference:
https://github.com/ai-se/Pits_lda/issues/20
