### ISSUE TITLE
need to comment on delta to google g=scholar

### ISSUE THREAD

**Issue by timm** [ai-se/citemap#2]
![image](https://cloud.githubusercontent.com/assets/29195/15589144/88bd0874-235f-11e6-9cd2-d0a7fd6141f6.png)

**Comment by bigfatnoob** [comment]
Conferences used in study:
- **ICSE**, International Conference on Software Engineering
- **ICSM**, International Conference on Software Maintainance
- **WCRE**, Working Conference on Reverse Engineering
- **CSMR**, European Conference on Software Maintenance and Reengineering 
- **MSR**, Mining Software Repositories
- **GPCE**, The International Conference on Generative Programming: Concepts & Experiences
- **FASE**, International Conference on Fundamental Approaches to Software Engineering
- **ICPC**, International Conference on Program Comprehension
- **FSE**, Foundations of Software Engineering
- **SCAM**, International Working Conference on Source Code Analysis and Manipulation
- **ASE**, Automated Software Engineering


Data from journals not available
