### ISSUE TITLE
Generate Ground Truth for communities.

### ISSUE THREAD

**Issue by bigfatnoob** [ai-se/citemap#21]
Refer: J. Yang and J. Leskovec. [Defining and Evaluating Network Communities based on Ground-truth](https://arxiv.org/pdf/1205.6233v3.pdf). ICDM, 2012.

Based on this paper they define Ground Truth as follows:

> The DBLP computer science bibliography provides a comprehensive list of research papers in computer science. We construct a co-authorship network where two authors are connected if they publish at least one paper together. Publication venue, e.g, journal or conference, defines an individual ground-truth community; authors who published to a certain journal or conference form a community.We regard each connected component in a group as a separate ground-truth community. We remove the ground-truth communities which have less than 3 nodes. We also provide the top 5,000 communities with highest quality which are described in our paper. As for the network, we provide the largest connected component.

**Comment by bigfatnoob** [comment]
Ground Truth Data : https://github.com/ai-se/citemap/blob/master/data/ground_truth_names.csv

**Comment by timm** [comment]
👍 💯
