### ISSUE TITLE
How Long Will This Live? Discovering the Lifespans of Software Engineering Ideas

### ISSUE THREAD

**Issue by bigfatnoob** [ai-se/citemap#22]
### Objective
Emperically determine halflife of SE topics

### Workflow
1. Determine topics using LDA. They use 80 topics on titles and abstracts when available
2. 
   1. They define Relative Half life as the period between which the importance of topic reduces to half.
   2. Two measures of importance are citation half life and publication half life
   3. They baseline against CHL and PHL

**Comment by timm** [comment]
do they call our to specific topics? which would be usable without amrit's results?

**Comment by bigfatnoob** [comment]
No they use all the 80 topics and reports decaying topics and sustaining topics. They said they tune the params using repeated runs to select the value with lowest log likelihood. No tuning like amrit's work

**Comment by timm** [comment]
@amritbhanu: see paper that used log likelihood to assess clusters. not sure if you should do the same ore merely mention them in your lit revies

**Comment by amritbhanu** [comment]
Right now we have been accessing the cluster using external measures like "jaccard".
But I can see if we get similar results using log likelihood.
