### ISSUE TITLE
RQ1: Topics in SE

### ISSUE THREAD

**Issue by bigfatnoob** [ai-se/citemap#25]
<img width="773" alt="screen shot 2016-11-15 at 1 09 25 pm" src="https://cloud.githubusercontent.com/assets/5582924/20317630/d3f3959e-ab34-11e6-8871-450450e3c336.png">

**Comment by timm** [comment]
oh man, this is so cool. i told sooooo many people about this work

still dont see why you are reporting > 7. humor me. please change

need tables of the **two** most cited papers in each of the above above topics:

- last 5 years
- all time

there was a complaint from reviewers that our graphics dont work in b&w.  i think the heatmaps work ok but the "history" diagram is the problem. any ideas? dont kill yourself on this one... maybe we just submit this as is to somewhere else and let reviewers trigger in random things (as they do) which may or may not be be the history diagram

____

here's one that i dont want you to DO, but think about. whats the effort about push back to 1991? Then we can claim 25 years of SE research.

**Comment by bigfatnoob** [comment]
on it
> still dont see why you are reporting > 7. humor me. please change

> need tables of the two most cited papers in each of the above above topics:
> 
> last 5 years
> all time

**Comment by bigfatnoob** [comment]
Updated the comment with 7 terms per topic
