### ISSUE TITLE
RQ6: What is the connection between a conferences program committee and the accepted papers?

### ISSUE THREAD

**Issue by bigfatnoob** [ai-se/citemap#28]
### PC HeatMap 2009-2016

![pc_heatmap_09_16](https://cloud.githubusercontent.com/assets/5582924/20107845/ff17b710-a5a7-11e6-9dd9-c65eb06e16d0.png)

### All HeatMap 2009-2016

![heatmap_09_16_dend](https://cloud.githubusercontent.com/assets/5582924/20107863/0f406010-a5a8-11e6-9894-70c6b4937951.png)

**Comment by timm** [comment]
as we said face to face: lets see

- the above 2 charts
- followed by a third table, of the same size, where each cell is the delta from PC to all

**Comment by bigfatnoob** [comment]
> as we said face to face: lets see
> 
> the above 2 charts
> followed by a third table, of the same size, where each cell is the delta from PC to all

**Comment by bigfatnoob** [comment]
The figures above have been updated. 

The figure below represents the delta between the topic distribution of conference for the PC to the topic distribution of the same conference for 'All Authors'. Light green indicates that a small increase in the topic published by the PC compared to 'All Authors'. Similarly Dark green indicates a large increase, light red indicates a small decrease and dark red indicates a large decrease. White indicates no change.

For example: look at MSR, there is hardly any delta between PC and All Authors

![delta](https://cloud.githubusercontent.com/assets/5582924/20316417/ba8005d4-ab2f-11e6-973c-4104b518d6e4.png)

**Comment by timm** [comment]
roger this
