### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by timm** [ai-se/citemap#3]
- amrit stability
- topics to conferences
- program committees to topics

- distinguished papers have no future
- all the conference s have the same topics
- is there a smaller saner number of conferences

**Comment by timm** [comment]
- super researchers: cover n topics
- is it better to cover N topics or 1 topic (are you more impactful)
- every conference has the same 
- conferences are highly biased
- higher accepted ra

- does pc biases == pattern of accepted papers
- rate of new authors arriving
- is there way  to predict if a topic will be hot or an author will be hot in 5 years time?
- death of author. can u predict?
- rise and fall of topic
- rise and fall of author
- does topic variability predict for success or failure?
- are their collaboration packs
- what are the collaboration packs?
- does membership of a pack predict for future success?

**Comment by timm** [comment]
- central people

**Comment by timm** [comment]
- will a paper be infuential
-

**Comment by bigfatnoob** [comment]
Heat maps.
