### ISSUE TITLE
Super Authors

### ISSUE THREAD

**Issue by bigfatnoob** [ai-se/citemap#4]
Are authors jack of all or masters of one?

**Comment by bigfatnoob** [comment]
### Topics Vs Authors
#### X-axis : Author IDs sorted in decreasing order of topics
#### Y-axis : Number of Topics

![super_author](https://cloud.githubusercontent.com/assets/5582924/15867173/f23d7d02-2caf-11e6-9e0e-9a399abafcd6.png)

### Authors vs Topics
#### X-axis : Number of Topics
#### Y-axis : Author Count

![super_author_bar](https://cloud.githubusercontent.com/assets/5582924/15867192/0b60a548-2cb0-11e6-84c2-fc4d5d7cd750.png)

**Comment by timm** [comment]
for the second graph, that is there any reason why "topics" is sorted that way? could not it be sorted left to right?. only and what is the total # of authors? about 2000? so 355 = 15%

also, please consider making these charts small enough to fit into a two-column paper. so smaller size, larger font

**Comment by bigfatnoob** [comment]
@timm the second graph is read as follows: the first bar represents authors who work  in 1 topic, the second bar represents authors who in 2 topics. In short nth bar represents authors who work in n topics.

The figure can be scaled. Figures 1 and 2 are essentially the same. Just flipped the x and y axes. Just wanted ur thoughts on which seemed better

**Comment by bigfatnoob** [comment]
## Updated Info

### Topics Vs Authors
#### X-axis : Author IDs sorted in decreasing order of topics
#### Y-axis : Number of Topics

![super_author](https://raw.githubusercontent.com/ai-se/citemap/master/figs/super_author/super_author.png)

### Authors vs Topics
#### X-axis : Number of Topics
#### Y-axis : Author Count

![super_author_bar](https://raw.githubusercontent.com/ai-se/citemap/master/figs/super_author/super_author_bar.png)

```
Topic 0: test, testing, cases, fault, tests, coverage, techniques, suite, generation, regression
Topic 1: applications, web, application, systems, service, security, services, aspect, business, oriented
Topic 2: patterns, pattern, anti, ibm, traits, micro, sub, 1800, assembler, catalog
Topic 3: code, source, tools, information, program, tool, refactoring, programming, developers, comprehension
Topic 4: optimal, search, spreadsheet, spreadsheets, methods, guarantee, sbse, factor, advantage, solutions
Topic 5: special, members, formal, methods, welcome, easier, conference, experiment, reasons, good
Topic 6: division, leads, vice, company, information, corporation, procurement, corporate, consolidation, robert
Topic 7: software, engineering, development, research, process, project, tools, paper, projects, work
Topic 8: program, analysis, programs, dynamic, data, technique, execution, static, approach, paper
Topic 9: model, design, software, based, systems, approach, paper, models, language, requirements
Topic 10: bug, bugs, reports, fix, report, fixing, fixed, fixes, crash, patches
Topic 11: software, code, approach, changes, paper, study, results, systems, source, analysis
```

**Comment by timm** [comment]
"Are authors jack of all or masters of one?"

Who are the super authors?

What makes for a super author?

**Comment by bigfatnoob** [comment]
Update staircase chart with most cited authors alone?

**Comment by bigfatnoob** [comment]
## Top 1% authors wrt to citations
### Topics vs Authors
#### X-axis : Author IDs sorted in decreasing order of topics
#### Y-axis : Number of Topics

![super_author](https://raw.githubusercontent.com/ai-se/citemap/master/figs/super_author/super_author_top.png)

### Authors vs Topics
#### X-axis : Number of Topics
#### Y-axis : Author Count

![super_author_bar](https://raw.githubusercontent.com/ai-se/citemap/master/figs/super_author/super_author_top_bar.png)

### Top authors publish in 10-12 topics. So for more reputation publish in more conferences
